name: wakatime-stats

on:
  schedule:
    - cron: '*/180 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          COMMIT_BY_ME: "True"
          COMMIT_MESSAGE: "Updated dev metrics"
          COMMIT_USERNAME: "oyi77"
          COMMIT_EMAIL: "mbahkoe.pendekar@gmail.com"
          WAKATIME_API_KEY: ${{ secrets.WAKA_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_COMMIT: "True"
          SHOW_LOC_CHART: "True"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_TOTAL_CODE_TIME: "False"
